try {
  throw ('help!');
}
catch(e){
  console.log('e', e);
}
